=== anoguero/whq-helper/WhqHelperApp/data/xml/monsters/whq-monster-schema.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     Warhammer Quest Monster and Event table schema.
    </xsd:documentation>
  </xsd:annotation>
  
  <xsd:simpleType name="intOrDashOrSpecial">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|-|S"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="ballisticSkillType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|Auto|-|S" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="attackType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|([0-9]*D6)|-|S" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="damageType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9]*D6)|([0-9]*D6\/[0-9]*D6\([0-9]\+\))|-|S" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:complexType name="ruleType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="id" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="magicType">
    <xsd:attribute name="id"    type="xsd:string"/>
    <xsd:attribute name="level" type="xsd:nonNegativeInteger"/>
  </xsd:complexType>
  
  <xsd:complexType name="specialType">
    <xsd:sequence>
      <xsd:element name="text" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="rule" type="ruleType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="magic" type="magicType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="monsterType">
    <xsd:all>
      <xsd:element name="wounds"         type="intOrDashOrSpecial" />
      <xsd:element name="move"           type="intOrDashOrSpecial" />
      <xsd:element name="weaponskill"    type="intOrDashOrSpecial" />
      <xsd:element name="ballisticskill" type="ballisticSkillType" />
      <xsd:element name="strength"       type="intOrDashOrSpecial" />
      <xsd:element name="toughness"      type="intOrDashOrSpecial" />
      <xsd:element name="initiative"     type="intOrDashOrSpecial" />
      <xsd:element name="attacks"        type="attackType" />
      <xsd:element name="gold"           type="intOrDashOrSpecial" />
      <xsd:element name="armor"          type="intOrDashOrSpecial" />
      <xsd:element name="damage"         type="damageType" />
      <xsd:element name="special"        type="specialType" />
    </xsd:all>
    <xsd:attribute name="id"       type="xsd:string" />
    <xsd:attribute name="name"     type="xsd:string" />
    <xsd:attribute name="plural"   type="xsd:string" />
    <xsd:attribute name="factions" type="xsd:string" />
  </xsd:complexType>


  <xsd:element name="monsters">
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="monster" type="monsterType" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== anoguero/whq-helper/WhqHelperApp/data/xml/monsters/rpbook-chaos-dwarfs.xml
<?xml version="1.0"?>

<monsters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	        xsi:noNamespaceSchemaLocation='whq-monster-schema.xsd'>
  <monster id="rpb-chaos-dwarf" factions="chaosdwarves" name="Chaos Dwarf" plural="Chaos Dwarfs">
    <wounds>8</wounds>
    <move>3</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>3</strength>
    <toughness>4</toughness>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>140</gold>
    <armor>2</armor>
    <damage>1D6/2D6(6+)</damage>
    <special>
      <rule id="rpb-magic-resistance" param="6+">Magic Resistance 6+</rule>
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-blunderbuss" 
           factions="chaosdwarves" name="Chaos Dwarf with Blunderbuss" 
           plural="Chaos Dwarfs with Blunderbuss">
    <wounds>8</wounds>
    <move>3</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>3</strength>
    <toughness>4</toughness>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>140</gold>
    <armor>1</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-armed-with" param="Blunderbuss">Armed with Blunderbuss</rule>
      <rule id="rpb-magic-resistance" param="6+">Magic Resistance 6+</rule>
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-champion" factions="chaosdwarves" name="Chaos Dwarf Champion" 
           plural="Chaos Dwarf Champions">
    <wounds>16</wounds>
    <move>3</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>3+</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>3</initiative>
    <attacks>2</attacks>
    <gold>480</gold>
    <armor>2</armor>
    <damage>2D6/3D6(5+)</damage>
    <special>
      <rule id="rpb-magic-resistance" param="6+">Magic Resistance 6+</rule>
      <rule id="rpb-magic-armour">Magic Armour</rule>
      <rule id="rpb-magic-item">Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-lord" factions="chaosdwarves" name="Chaos Dwarf Lord" 
           plural="Chaos Dwarf Lords">
    <wounds>33</wounds>
    <move>3</move>
    <weaponskill>7</weaponskill>
    <ballisticskill>1+</ballisticskill>
    <strength>4</strength>
    <toughness>5</toughness>
    <initiative>5</initiative>
    <attacks>4</attacks>
    <gold>1600</gold>
    <armor>3</armor>
    <damage>3D6</damage>
    <special>
      <rule id="rpb-magic-resistance" param="5+">Magic Resistance 5+</rule>
      <rule id="rpb-magic-armour">Magic Armour</rule>
      <rule id="rpb-magic-item">2 x Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-sorcerer" factions="chaosdwarves" name="Chaos Dwarf Sorcerer" 
           plural="Chaos Dwarf Sorcerers">
    <wounds>8</wounds>
    <move>3</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>3</strength>
    <toughness>6</toughness>
    <initiative>3</initiative>
    <attacks>1</attacks>
    <gold>590</gold>
    <armor>2</armor>
    <damage>1D6/2D6(6+)</damage>
    <special>
      <rule id="rpb-magic-dispel" param="4+">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance" param="4+">Magic Resistance 4+</rule>
      <rule id="rpb-protection-ring" param="+1 T">Protection Ring (+1 T)</rule>
      <magic id="rpb-chaos-dwarf" level="1" />
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-master-sorcerer" 
           factions="chaosdwarves" name="Chaos Dwarf Master Sorcerer" 
           plural="Chaos Dwarf Master Sorcerers">
    <wounds>26</wounds>
    <move>3</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>4</strength>
    <toughness>5</toughness>
    <initiative>4</initiative>
    <attacks>2</attacks>
    <gold>2190</gold>
    <armor>3</armor>
    <damage>2D6</damage>
    <special>
      <rule id="rpb-magic-dispel" param="4+">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance" param="4+">Magic Resistance 4+</rule>
      <rule id="rpb-magic-armour">Magic Armour; Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
      <magic id="rpb-chaos-dwarf" level="3" />
    </special>
  </monster>
  <monster id="rpb-chaos-dwarf-sorcerer-lord" factions="chaosdwarves" name="Chaos Dwarf Sorcerer Lord" 
           plural="Chaos Dwarf Sorcerer Lord">
    <wounds>40</wounds>
    <move>3</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>4</strength>
    <toughness>5</toughness>
    <initiative>5</initiative>
    <attacks>3</attacks>
    <gold>3280</gold>
    <armor>3</armor>
    <damage>3D6/4D6(5+)</damage>
    <special>
      <rule id="rpb-magic-dispel" param="4+">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance" param="3+">Magic Resistance 3+</rule>
      <rule id="rpb-magic-armour">Magic Armour</rule>
      <rule id="rpb-magic-item">3 x Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
      <magic id="rpb-chaos-dwarf" level="4" />
    </special>
  </monster>
</monsters>

=== anoguero/whq-helper/WhqHelperApp/data/xml/monsters/hothq-monsters.xml
<?xml version="1.0"?>

<monsters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation='whq-monster-schema.xsd'>
  <monster id="hothq-black-dragon" factions="darkelves chaos" name="Black Dragon" plural="Black Dragons">
    <move>6</move>
    <weaponskill>6</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>6</strength>
    <toughness>6</toughness>
    <wounds>74</wounds>
    <initiative>8</initiative>
    <attacks>7</attacks>
    <gold>4500</gold>
    <armor>6</armor>
    <damage>6D6</damage>
    <special>
      <rule id="hothq-breathes-smoke">Breathes Smoke (Ambush, Magic A)</rule>
      <rule id="rpb-fly">Fly</rule>
      <rule id="rpb-ignore-blows">Ignore Blows 5+</rule>
      <rule id="rpb-ignore-pain">Ignore Pain 7</rule>
      <rule id="rpb-large-monster">Large Monster</rule>
      <rule id="rpb-terror">Terror 12</rule>
      <rule id="rpb-treasure-hoard">Treasure Hoard +0</rule>
    </special>
  </monster>
  <monster id="hothq-cave-dragon" factions="chaos darkelves" name="Cave Dragon" plural="Cave Dragons">
    <move>8</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>5</strength>
    <toughness>5</toughness>
    <wounds>35</wounds>
    <initiative>6</initiative>
    <attacks>3</attacks>
    <gold>910</gold>
    <armor>3</armor>
    <damage>3D6/4D6(5+)</damage>
    <special>
      <rule id="hothq-breathes-noxious-vapour">Breathes Noxious Vapour 4+</rule>
      <rule id="rpb-fear">Fear 10</rule>
      <rule id="rpb-fly">Fly</rule>
      <rule id="rpb-plague">Plague</rule>
    </special>
  </monster>
  <monster id="hothq-cave-troll" factions="chaos orcs darkelves" name="Cave Troll" plural="Cave Trolls">
    <move>6</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>6+</ballisticskill>
    <strength>5</strength>
    <toughness>4</toughness>
    <wounds>30</wounds>
    <initiative>1</initiative>
    <attacks>3</attacks>
    <gold>650</gold>
    <armor>-</armor>
    <damage>2D6</damage>
    <special>
      <rule id="rpb-fear">Fear 6</rule>
      <rule id="rpb-regenerate">Regenerate 2</rule>
      <rule id="rpb-vomit">Vomit</rule>
    </special>
  </monster>
  <monster id="hothq-emperor-black-dragon" factions="darkelves chaos" name="Emperor Black Dragon" plural="Emperor Black Dragons">
    <move>6</move>
    <weaponskill>8</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>8</strength>
    <toughness>8</toughness>
    <wounds>94</wounds>
    <initiative>10</initiative>
    <attacks>9</attacks>
    <gold>7500</gold>
    <armor>8</armor>
    <damage>7D6</damage>
    <special>
      <rule id="hothq-breathes-smoke">Breathes Smoke (Ambush, Magic A)</rule>
      <rule id="rpb-fly">Fly</rule>
      <rule id="rpb-ignore-blows">Ignore Blows 4+</rule>
      <rule id="rpb-ignore-pain">Ignore Pain 3D6</rule>
      <rule id="rpb-large-monster">Large Monster</rule>
      <rule id="rpb-terror">Terror 14</rule>
      <rule id="rpb-treasure-hoard">Treasure Hoard +2</rule>
      <magic id="rpb-chaos" level="2" />
    </special>
  </monster>
  <monster id="hothq-great-black-dragon" factions="darkelves chaos" name="Great Black Dragon" plural="Great Black Dragons">
    <move>6</move>
    <weaponskill>7</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>7</strength>
    <toughness>7</toughness>
    <wounds>84</wounds>
    <initiative>9</initiative>
    <attacks>8</attacks>
    <gold>6000</gold>
    <armor>7</armor>
    <damage>6D6</damage>
    <special>
      <rule id="hothq-breathes-smoke">Breathes Smoke (Ambush, Magic A)</rule>
      <rule id="rpb-fly">Fly</rule>
      <rule id="rpb-ignore-blows">Ignore Blows 4+</rule>
      <rule id="rpb-ignore-pain">Ignore Pain 7</rule>
      <rule id="rpb-large-monster">Large Monster</rule>
      <rule id="rpb-terror">Terror 13</rule>
      <rule id="rpb-treasure-hoard">Treasure Hoard +1</rule>
      <magic id="rpb-chaos" level="1" />
    </special>
  </monster>
  <monster id="hothq-ogre-mercenary" factions="chaos darkelves" name="Ogre Mercenary" plural="Ogre Mercenaries">
    <move>6</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>5+</ballisticskill>
    <strength>4</strength>
    <toughness>5</toughness>
    <wounds>13</wounds>
    <initiative>3</initiative>
    <attacks>2</attacks>
    <gold>400</gold>
    <armor>-</armor>
    <damage>2D6/3D6(5+)</damage>
    <special>
      <rule id="rpb-fear">Fear 5</rule>
    </special>
  </monster>
  <monster id="hothq-ogre-mercenary-champion" factions="chaos darkelves" name="Ogre Mercenary Champion" plural="Ogre Mercenary Champions">
    <move>6</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>5</strength>
    <toughness>5</toughness>
    <wounds>24</wounds>
    <initiative>4</initiative>
    <attacks>3</attacks>
    <gold>1000</gold>
    <armor>1</armor>
    <damage>3D6/4D6(5+)</damage>
    <special>
      <rule id="rpb-fear">Fear 6</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="hothq-river-troll" factions="chaos orcs darkelves" name="River Troll" plural="River Trolls">
    <move>6</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>6+</ballisticskill>
    <strength>5</strength>
    <toughness>4</toughness>
    <wounds>25</wounds>
    <initiative>1</initiative>
    <attacks>3</attacks>
    <gold>650</gold>
    <armor>-</armor>
    <damage>2D6</damage>
    <special>
      <rule id="hothq-slimy-skin">Slimy Skin</rule>
      <rule id="rpb-fear">Fear 6</rule>
      <rule id="rpb-regenerate">Regenerate 2</rule>
    </special>
  </monster>
</monsters>

=== anoguero/whq-helper/WhqHelperApp/data/xml/monsters/originaldeck-monsters.xml
<?xml version="1.0"?>

<monsters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	        xsi:noNamespaceSchemaLocation='whq-monster-schema.xsd'>

  <monster id="od-giant-bat" name="Giant Bat" plural="Giant Bats">
    <move>8</move>
    <weaponskill>2</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>2</strength>
    <toughness>2</toughness>
    <wounds>1</wounds>
    <initiative>-</initiative>
    <attacks>1</attacks>
    <gold>15</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text>Giant Bats make an immediate attack as soon as they are placed on the board and then attack as normal in the Monsters' Phase.
After the first Turn, the combat sequence returns to normal.
Bats are never pinned and will change target each turn if possible.</text></special>
  </monster>
  <monster id="od-giant-rat" name="Giant Rat" plural="Giant Rats">
    <move>6</move>
    <weaponskill>2</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <wounds>1</wounds>
    <initiative>4</initiative>
    <attacks>1</attacks>
    <gold>25</gold>
    <armor>-</armor>
    <damage>5D6</damage>
    <special><text>When a Giant Rat hits your Warrior, roll 2 dice to see how many Wounds it causes, and add its Strength (2) to the score.
Once a Giant Rat has attacked your Warrior, roll 1D6.  On a 3+ the Giant Rat's sucidial, frenzied attack has opened it up to your Warrior's attacks and he kills it automatically.</text></special>
  </monster>
  <monster id="od-giant-spider" name="Giant Spider" plural="Giant Spiders">
    <move>6</move>
    <weaponskill>2</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>S</strength>
    <toughness>2</toughness>
    <wounds>1</wounds>
    <initiative>-</initiative>
    <attacks>1</attacks>
    <gold>15</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text>If a Spider attacks a Warrior who is already webbed, the Spider automatically bites him inflicting 1D3 Wounds with no modifiers for Toughness or armour.
If the Warrior wasn't already webbed, make a roll to hit.  If the Spider hits, the Warrior is now webbed and may do nothing until he gets free.  Put a Webbed counter next to him.
At the start of each turn roll 1D6 for each webbed Warrior and add his Strength.  If the total is 7 or more, he frees himself and may act normally.</text></special>
  </monster>
  <monster id="od-snotling" name="Snotling" plural="Snotlings">
    <move>4</move>
    <weaponskill>1</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>1</strength>
    <toughness>1</toughness>
    <wounds>1</wounds>
    <initiative>1</initiative>
    <attacks>1</attacks>
    <gold>10</gold>
    <armor>-</armor>
    <damage>S</damage>
    <special><text>Snotlings make an immediate attack as soon as they are placed on the board and then attack as normal in the Monsters' Phase.
Draw a Warrior counter and place as many Snotlings as you can around that Warrior.  Repeat until all the Snotlings have been placed.
For each Snotling above one in combat with a Warrior, add +1 to their hit roll and increase their Strength by +1: e.g., 4 Snotlings make a single Strength 4 attack with +3 on the to hit roll.
Snotlings do not switch attacks unless their target dies, and will fight until killed.</text></special>
  </monster>
  <monster id="od-goblin-archer" name="Goblin Archer" plural="Goblin Archers">
    <move>4</move>
    <weaponskill>2</weaponskill>
    <ballisticskill>5+</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <wounds>2</wounds>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>20</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text>When shooting with their bows, Night Goblin archers need to roll a 5 or more to hit.  A Goblin's bow has Stength 1, and causes 1D6+1 Wounds.
Before fighting the Night Goblin archers, take another Event card.</text></special>
  </monster>
  <monster id="od-goblin-spearman" 
           name="Goblin Spearman" plural="Goblin Spearmen">
    <move>4</move>
    <weaponskill>2</weaponskill>
    <ballisticskill>5+</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <wounds>2</wounds>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>20</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text>When shooting with their bows, Night Goblin archers need to roll a 5 or more to hit.  A Goblin's bow has Stength 1, and causes 1D6+1 Wounds.
Goblins armed with spears may attack from 2 squares away, even past intervening Monsters and Warriors.</text></special>
  </monster>
  <monster id="od-skaven" name="Skaven" plural="Skaven">
    <move>5</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <wounds>3</wounds>
    <initiative>4</initiative>
    <attacks>1</attacks>
    <gold>40</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text></text></special>
  </monster>
  <monster id="od-orc" name="Orc" plural="Orcs">
    <move>4</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>3</strength>
    <toughness>4</toughness>
    <wounds>3</wounds>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>55</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text></text></special>
  </monster>
  <monster id="od-orc-archer" name="Orc Archer" plural="Orc Archers">
    <move>4</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>3</strength>
    <toughness>4</toughness>
    <wounds>3</wounds>
    <initiative>2</initiative>
    <attacks>1</attacks>
    <gold>55</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special><text>When shooting with their bows, Orc archers need to roll a 4 or more to hit.  An Orc's bow has Strength 3, and causes 1D6+3 Wounds.</text></special>
  </monster>
  <monster id="od-minotaur-solo" name="Minotaur" plural="Minotaurs">
    <move>6</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <wounds>15</wounds>
    <initiative>3</initiative>
    <attacks>2</attacks>
    <gold>440</gold>
    <armor>-</armor>
    <damage>2D6</damage>
    <special><text>When a Minotaur hits a Warrior, roll 2 dice to see how many Wounds it causes, adding its Strength of 4 to the total.
Before fighting the Minotaur, take another Event card.  If this is an Event, resolve it before fighting the Minotaur.  If it reveals more Monsters, fight them all at once.</text></special>
  </monster>
  <monster id="od-minotaur" name="Minotaur" plural="Minotaurs">
    <move>6</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>4+</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <wounds>15</wounds>
    <initiative>3</initiative>
    <attacks>2</attacks>
    <gold>440</gold>
    <armor>-</armor>
    <damage>2D6</damage>
    <special><text>When a Minotaur hits a Warrior, roll 2 dice to see how many Wounds it causes, adding its Strength of 4 to the total.</text></special>
  </monster>
</monsters>

=== anoguero/whq-helper/WhqHelperApp/data/xml/monsters/userdefined-monsters.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<monsters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="whq-monster-schema.xsd">
  <monster factions="chaos" id="chaos-thug" name="Chaos Thug" plural="Chaos Thugs">
    <wounds>7</wounds>
    <move>4</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>3+</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <initiative>3</initiative>
    <attacks>1</attacks>
    <gold>50</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-ambush" param="5+">AMBUSH 5+</rule>
    </special>
  </monster>
</monsters>

=== anoguero/whq-helper/WhqHelperApp/data/xml/monsters/cot-monsters.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<monsters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="whq-monster-schema.xsd">
  <monster factions="undead" id="cot-carrion" name="Carrion" plural="Carrions">
    <wounds>10</wounds>
    <move>8</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <initiative>4</initiative>
    <attacks>3</attacks>
    <gold>450</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="cot-carrion-attack">Carrion Attack (Ambush, Magic A)</rule>
      <rule id="rpb-fear" param="6">Fear 6</rule>
      <rule id="rpb-fly">Fly</rule>
    </special>
  </monster>
  <monster factions="undead" id="cot-dread-king" name="The Dread King" plural="Dread Kings">
    <wounds>34</wounds>
    <move>6</move>
    <weaponskill>1</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>5</strength>
    <toughness>4</toughness>
    <initiative>5</initiative>
    <attacks>4</attacks>
    <gold>2780</gold>
    <armor>3</armor>
    <damage>3D6</damage>
    <special>
      <rule id="rpb-magic-dispel" param="4+">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance" param="4+">Magic Resistance 4+</rule>
      <rule id="cot-undead-magic-item">3 x Magic Items</rule>
      <rule id="cot-undead-magic-weapon">Magic Weapon</rule>
      <rule id="rpb-regenerate" param="2">Regenerate 2</rule>
      <magic id="rpb-necromantic" level="3"/>
    </special>
  </monster>
  <monster factions="undead" id="cot-gunther-laranscheld" name="Gunther Laranscheld" plural="Gunther Laranscheld">
    <wounds>15</wounds>
    <move>4</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3+</ballisticskill>
    <strength>4</strength>
    <toughness>3</toughness>
    <initiative>3</initiative>
    <attacks>2</attacks>
    <gold>550</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="cot-grimoire-necris">Grimoire Necris</rule>
      <rule id="cot-minions">Minions</rule>
      <magic id="rpb-necromantic" level="1"/>
    </special>
  </monster>
  <monster factions="undead" id="cot-luthor" name="Luthor" plural="Luthor">
    <wounds>8</wounds>
    <move>4</move>
    <weaponskill>3</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>5</strength>
    <toughness>5</toughness>
    <initiative>4</initiative>
    <attacks>1</attacks>
    <gold>300</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-ignore-blows" param="6+">Ignore Blows 6+</rule>
      <rule id="cot-luthor-special-attack">Special Attack</rule>
    </special>
  </monster>
  <monster factions="undead" id="cot-zombie-dragon" name="Zombie Dragon" plural="Zombie Dragons">
    <wounds>75</wounds>
    <move>6</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>-</ballisticskill>
    <strength>7</strength>
    <toughness>6</toughness>
    <initiative>3</initiative>
    <attacks>6</attacks>
    <gold>5000</gold>
    <armor>8</armor>
    <damage>6D6</damage>
    <special>
      <rule id="rpb-fly">Fly</rule>
      <rule id="rpb-ignore-blows" param="4+">Ignore Blows 4+</rule>
      <rule id="rpb-ignore-pain" param="7">Ignore Pain 7</rule>
      <rule id="rpb-large-monster">Large Monster</rule>
      <rule id="cot-pestilential-breath">Pestilential Breath (Ambush, Magic A)</rule>
      <rule id="rpb-plague">Plague</rule>
      <rule id="rpb-terror" param="13">Terror 13</rule>
    </special>
  </monster>
</monsters>
