=== anoguero/whq-helper/WhqHelperApp/data/xml/monsters/whq-monster-schema.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     Warhammer Quest Monster and Event table schema.
    </xsd:documentation>
  </xsd:annotation>
  
  <xsd:simpleType name="intOrDashOrSpecial">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|-|S"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="ballisticSkillType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|Auto|-|S" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="attackType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|([0-9]*D6)|-|S" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="damageType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9]*D6)|([0-9]*D6\/[0-9]*D6\([0-9]\+\))|-|S" />
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:complexType name="ruleType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="id" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="magicType">
    <xsd:attribute name="id"    type="xsd:string"/>
    <xsd:attribute name="level" type="xsd:nonNegativeInteger"/>
  </xsd:complexType>
  
  <xsd:complexType name="specialType">
    <xsd:sequence>
      <xsd:element name="text" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="rule" type="ruleType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="magic" type="magicType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="monsterType">
    <xsd:all>
      <xsd:element name="wounds"         type="intOrDashOrSpecial" />
      <xsd:element name="move"           type="intOrDashOrSpecial" />
      <xsd:element name="weaponskill"    type="intOrDashOrSpecial" />
      <xsd:element name="ballisticskill" type="ballisticSkillType" />
      <xsd:element name="strength"       type="intOrDashOrSpecial" />
      <xsd:element name="toughness"      type="intOrDashOrSpecial" />
      <xsd:element name="initiative"     type="intOrDashOrSpecial" />
      <xsd:element name="attacks"        type="attackType" />
      <xsd:element name="gold"           type="intOrDashOrSpecial" />
      <xsd:element name="armor"          type="intOrDashOrSpecial" />
      <xsd:element name="damage"         type="damageType" />
      <xsd:element name="special"        type="specialType" />
    </xsd:all>
    <xsd:attribute name="id"       type="xsd:string" />
    <xsd:attribute name="name"     type="xsd:string" />
    <xsd:attribute name="plural"   type="xsd:string" />
    <xsd:attribute name="factions" type="xsd:string" />
  </xsd:complexType>


  <xsd:element name="monsters">
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="monster" type="monsterType" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== anoguero/whq-helper/WhqHelperApp/data/xml/monsters/rpbook-dark-elves.xml
<?xml version="1.0"?>

<monsters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	        xsi:noNamespaceSchemaLocation='whq-monster-schema.xsd'>
  <monster id="rpb-dark-elf-warrior" factions="darkelves" name="Dark Elf Warrior" 
           plural="Dark Elf Warriors">
    <wounds>6</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3+</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <initiative>6</initiative>
    <attacks>1</attacks>
    <gold>100</gold>
    <armor>1</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-armed-with" param="Crossbows (Str 4)">Armed with Crossbows (Str 4)</rule>
      <rule id="rpb-dodge" param="6+">Dodge 6+</rule>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-champion" factions="darkelves" name="Dark Elf Champion" 
           plural="Dark Elf Champions">
    <wounds>14</wounds>
    <move>5</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>5+</ballisticskill>
    <strength>4</strength>
    <toughness>3</toughness>
    <initiative>7</initiative>
    <attacks>2</attacks>
    <gold>480</gold>
    <armor>2</armor>
    <damage>2D6</damage>
    <special>
      <rule id="rpb-dodge" param="6+">Dodge 6+</rule>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-hero" factions="darkelves" name="Dark Elf Hero" plural="Dark Elf Heroes">
    <wounds>25</wounds>
    <move>5</move>
    <weaponskill>6</weaponskill>
    <ballisticskill>1+</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>8</initiative>
    <attacks>3</attacks>
    <gold>1040</gold>
    <armor>4</armor>
    <damage>2D6</damage>
    <special>
      <rule id="rpb-dodge" param="4+">Dodge 4+</rule>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
      <rule id="rpb-magic-resistance" param="5+">Magic Resistance 5+</rule>
      <rule id="rpb-magic-armour">Magic Armour</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-lord" factions="darkelves" name="Dark Elf Lord" plural="Dark Elf Lords">
    <wounds>34</wounds>
    <move>5</move>
    <weaponskill>7</weaponskill>
    <ballisticskill>A</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>9</initiative>
    <attacks>4</attacks>
    <gold>1600</gold>
    <armor>4</armor>
    <damage>3D6</damage>
    <special>
      <rule id="rpb-dodge" param="4+">Dodge 4+</rule>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
      <rule id="rpb-magic-resistance" param="5+">Magic Resistance 5+</rule>
      <rule id="rpb-magic-armour">Magic Armour</rule>
      <rule id="rpb-magic-item">2 x Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-assassin" factions="darkelves" name="Dark Elf Assassin" 
           plural="Dark Elf Assassins">
    <wounds>12</wounds>
    <move>5</move>
    <weaponskill>9</weaponskill>
    <ballisticskill>A</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>10</initiative>
    <attacks>2</attacks>
    <gold>410</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-ambush-magic" param="5+">Ambush, Magic 5+</rule>
      <rule id="rpb-assassinate" param="6+">Assassinate 6+</rule>
      <rule id="rpb-dodge" param="5+">Dodge 5+</rule>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
      <rule id="rpb-weeping-blade">Weeping Blades</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-beastmaster" factions="darkelves" name="Dark Elf Beastmaster" 
           plural="Dark Elf Beastmasters">
    <wounds>15</wounds>
    <move>5</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>2+</ballisticskill>
    <strength>4</strength>
    <toughness>3</toughness>
    <initiative>7</initiative>
    <attacks>2</attacks>
    <gold>150</gold>
    <armor>2</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-armed-with" param="Crossbow (Str 5)">Armed with Crossbow (Str 5)</rule>
      <rule id="rpb-beast-handler">Beast Handler</rule>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
    </special>
  </monster>
  <monster id="rpb-dark-elf-sorcerer" factions="darkelves" name="Dark Elf Sorcerer" 
           plural="Dark Elf Sorcerers">
    <wounds>12</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3+</ballisticskill>
    <strength>3</strength>
    <toughness>4</toughness>
    <initiative>7</initiative>
    <attacks>1</attacks>
    <gold>590</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
      <rule id="rpb-magic-resistance" param="6+">Magic Resistance 6+</rule>
      <rule id="rpb-magic-item">Magic Item</rule>
      <magic id="rpb-dark-elf" level="1" />
    </special>
  </monster>
  <monster id="rpb-dark-elf-sorcerer-champion" factions="darkelves" name="Dark Elf Sorcerer Champion"    
           plural="Dark Elf Sorcerer Champions">
    <wounds>20</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3+</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>7</initiative>
    <attacks>1</attacks>
    <gold>1210</gold>
    <armor>1</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
      <rule id="rpb-magic-resistance" param="5+">Magic Resistance 5+</rule>
      <rule id="rpb-magic-item">Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
      <magic id="rpb-dark-elf" level="2" />
    </special>
  </monster>
  <monster id="rpb-dark-elf-master-sorcerer" factions="darkelves" name="Dark Elf Master Sorcerer"
           plural="Dark Elf Master Sorcerer">
    <wounds>30</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3+</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>8</initiative>
    <attacks>2</attacks>
    <gold>2190</gold>
    <armor>2</armor>
    <damage>2D6</damage>
    <special>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
      <rule id="rpb-magic-dispel" param="4+">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance" param="4+">Magic Resistance 4+</rule>
      <rule id="rpb-magic-item">2 x Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
      <magic id="rpb-dark-elf" level="3" />
    </special>
  </monster>
  <monster id="rpb-dark-elf-sorcerer-lord" factions="darkelves" name="Dark Elf Sorcerer Lord"
           plural="Dark Elf Socrerer Lords">
    <wounds>41</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3+</ballisticskill>
    <strength>4</strength>
    <toughness>4</toughness>
    <initiative>9</initiative>
    <attacks>3</attacks>
    <gold>3280</gold>
    <armor>3</armor>
    <damage>3D6</damage>
    <special>
      <rule id="rpb-ambush-magic" param="A">Ambush, Magic A</rule>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
      <rule id="rpb-magic-dispel" param="4+">Magic Dispel 4+</rule>
      <rule id="rpb-magic-resistance" param="3+">Magic Resistance 3+</rule>
      <rule id="rpb-magic-item">3 x Magic Item</rule>
      <rule id="rpb-magic-weapon">Magic Weapon</rule>
      <magic id="rpb-dark-elf" level="4" />
    </special>
  </monster>
  <monster id="rpb-dark-elf-naggaroth-black-guard"
           factions="darkelves" name="Dark Elf Naggaroth Black Guard" 
           plural="Dark Elf Naggaroth Black Guards">
    <wounds>6</wounds>
    <move>5</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>3+</ballisticskill>
    <strength>4</strength>
    <toughness>3</toughness>
    <initiative>7</initiative>
    <attacks>1</attacks>
    <gold>150</gold>
    <armor>2</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-armed-with" param="Halberds">Armed with Halberds</rule>
      <rule id="rpb-fight-in-ranks">Fight in Ranks</rule>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
    </special>
  </monster>
  <monster id="rpb-witch-elf" factions="darkelves" name="Witch Elf" plural="Witch Elves">
    <wounds>11</wounds>
    <move>5</move>
    <weaponskill>4</weaponskill>
    <ballisticskill>3+</ballisticskill>
    <strength>3</strength>
    <toughness>3</toughness>
    <initiative>6</initiative>
    <attacks>1</attacks>
    <gold>140</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-frenzy" param="4+">Frenzy 4+</rule>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
    </special>
  </monster>
  <monster id="rpb-witch-elf-champion" factions="darkelves" name="Witch Elf Champion" 
           plural="Witch Elf Champions">
    <wounds>13</wounds>
    <move>5</move>
    <weaponskill>5</weaponskill>
    <ballisticskill>2+</ballisticskill>
    <strength>4</strength>
    <toughness>3</toughness>
    <initiative>7</initiative>
    <attacks>2</attacks>
    <gold>600</gold>
    <armor>-</armor>
    <damage>1D6</damage>
    <special>
      <rule id="rpb-frenzy" param="3+">Frenzy 3+</rule>
      <rule id="rpb-hate" param="Elves">Hate Elves</rule>
    </special>
  </monster>
</monsters>
