=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/whq-tables-schema.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     Warhammer Quest Monster and Event table schema.
    </xsd:documentation>
  </xsd:annotation>
  
  <xsd:simpleType name="monsterNumberType">
   <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|([0-9]*-[0-9]*)|S|S \(mounts\)"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ambienceValueType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="chaos"/>
      <xsd:enumeration value="undead"/>
      <xsd:enumeration value="skaven"/>
      <xsd:enumeration value="orcs"/>
      <xsd:enumeration value="chaos-dwarves"/>
      <xsd:enumeration value="dark-elves"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ambiencesType">
    <xsd:list itemType="ambienceValueType"/>
  </xsd:simpleType>
  
  <xsd:complexType name="magicType">
    <xsd:attribute name="id"    type="xsd:string"/>
    <xsd:attribute name="level" type="xsd:nonNegativeInteger"/>
  </xsd:complexType>
  
  <xsd:complexType name="ruleType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="param" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  
  <xsd:complexType name="specialType">
    <xsd:sequence>
      <xsd:element name="text" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="rule" type="ruleType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="magic" type="magicType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="append" type="xsd:boolean" />
  </xsd:complexType>
  
  <xsd:complexType name="monsterType">
    <xsd:sequence minOccurs="0" maxOccurs="1">
      <xsd:element name="special" type="specialType" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="number" type="monsterNumberType" />
    <xsd:attribute name="level" type="xsd:integer" />
    <xsd:attribute name="ambiences" type="ambiencesType" />
  </xsd:complexType>
  
  <xsd:complexType name="eventType">
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="ambiences" type="ambiencesType" />
  </xsd:complexType>
  
  <xsd:complexType name="groupType">
    <xsd:sequence minOccurs="1" maxOccurs="unbounded">
      <xsd:element name="monster" type="monsterType" />
    </xsd:sequence>
    <xsd:attribute name="level" type="xsd:integer" />
  </xsd:complexType>

  <xsd:complexType name="tableRefType">
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="level" type="xsd:integer" />
    <xsd:attribute name="targetLevel" type="xsd:integer" />
    <xsd:attribute name="times" type="xsd:positiveInteger" />
    <xsd:attribute name="ambiences" type="ambiencesType" />
  </xsd:complexType>
  
  <xsd:complexType name="tableType">
    <xsd:sequence maxOccurs="unbounded" minOccurs="1">
      <xsd:choice>
        <xsd:element name="monster" type="monsterType" />
        <xsd:element name="event" type="eventType" />
        <xsd:element name="group" type="groupType" />
        <xsd:element name="tableRef" type="tableRefType" />
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="kind" type="xsd:string" />
  </xsd:complexType>

  <xsd:element name="tables">
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="table" type="tableType" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
</xsd:schema>

=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/rpbook-settlement-event-table.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="Roleplay Book Settlement Events Table" kind="settlement">
    <event id="rpb-thrown-out" />
    <event id="rpb-settlement-12-pickpocket" />
    <event id="rpb-settlement-13-uneventful-day" />
    <event id="rpb-settlement-14-good-deed" />
    <event id="rpb-settlement-15-investment" />
    <event id="rpb-settlement-16-steam-bath" />
    <event id="rpb-settlement-21-fight" />
    <event id="rpb-settlement-22-uneventful-day" />
    <event id="rpb-settlement-23-fooled" />
    <event id="rpb-settlement-24-circus" />
    <event id="rpb-settlement-25-reward" />
    <event id="rpb-settlement-26-betrothed" />
    <event id="rpb-settlement-31-drugged" />
    <event id="rpb-settlement-32-uneventful-day" />
    <event id="rpb-settlement-33-an-honest-days-work" />
    <event id="rpb-settlement-34-riotous-living" />
    <event id="rpb-settlement-35-duel" />
    <event id="rpb-settlement-36-uneventful-day" />
    <event id="rpb-settlement-41-gambling" />
    <event id="rpb-settlement-42-uneventful-day" />
    <event id="rpb-settlement-43-join-the-watch" />
    <event id="rpb-settlement-44-illness" />
    <event id="rpb-settlement-45-pet-dog" />
    <event id="rpb-settlement-46-runaway" />
    <event id="rpb-settlement-51-crime" />
    <event id="rpb-settlement-52-uneventful-day" />
    <event id="rpb-settlement-53-counterfeit" />
    <event id="rpb-settlement-54-beggars" />
    <event id="rpb-settlement-55-debt" />
    <event id="rpb-settlement-56-uneventful-day" />
    <event id="rpb-settlement-61-temple-donation" />
    <event id="rpb-settlement-62-uneventful-day" />
    <event id="rpb-settlement-63-hunting" />
    <event id="rpb-settlement-64-witchcraft" />
    <event id="rpb-settlement-65-uneventful-day" />
    <event id="rpb-settlement-66-accident" />
  </table>
</tables>

=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/gpt-events-table.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="ChatGPT Dungeon Events">
    <event id="gpt-glyph-of-hashut" />
    <event id="gpt-ratling-snare" />
    <event id="gpt-orc-drop-net" />
    <event id="gpt-falling-idol" />
    <event id="gpt-grudge-axes" />
    <event id="gpt-bad-moon-spores" />
    <event id="gpt-wardstone-spark" />
    <event id="gpt-poison-censer" />
    <event id="gpt-blood-runes" />
    <event id="gpt-knife-slot" />
    <event id="gpt-false-floor" />
    <event id="gpt-screaming-skulls" />
    <event id="gpt-cold-fire" />
    <event id="gpt-blackpowder-cache" />
    <event id="gpt-midden-leeches" />
    <event id="gpt-shrine-of-morr" />
    <event id="gpt-dwarfen-waystones" />
    <event id="gpt-skaven-scratchings" />
    <event id="gpt-bretonnian-vow" />
    <event id="gpt-pilgrim-bones" />
    <event id="gpt-smugglers-cache" />
    <event id="gpt-lost-lamplighter" />
    <event id="gpt-echo-of-nagash" />
    <event id="gpt-squig-mushroom-bed" />
    <event id="gpt-river-of-filth" />
    <event id="gpt-sealed-ossuary" />
    <event id="gpt-mercenary-map" />
    <event id="gpt-ancestor-mask" />
    <event id="gpt-sigmarite-reliquary" />
    <event id="gpt-ghoul-feast" />
    <event id="gpt-runes-of-warning" />
    <event id="gpt-thief-in-the-dark" />
    <event id="gpt-fungus-brew" />
    <event id="gpt-forgotten-gaol" />
    <event id="gpt-chaos-dwarf-ledger" />
    <event id="gpt-moonlit-well" />
    <event id="gpt-plague-cart" />
    <event id="gpt-watchers-in-the-stone" />
    <event id="gpt-last-stand" />
    <event id="gpt-tunnel-tax" />
    <event id="gpt-hermit-seer" />
    <event id="gpt-grave-sand" />
    <event id="gpt-echoing-horn" />
    <event id="gpt-vault-of-oaths" />
    <event id="gpt-hunters-mark" />
    <event id="gpt-ghostly-masons" />
    <event id="gpt-silent-bell" />
    <event id="gpt-banner-in-the-dust" />
    <event id="gpt-lahmian-mirror" />
    <event id="gpt-slayers-cairn" />
    <event id="gpt-brimstone-vent" />
    <event id="gpt-gutter-runner-dart" />
    <event id="gpt-doomwheel-surge" />
    <event id="gpt-frost-rime-trap" />
    <event id="gpt-chain-flail-pendulum" />
    <event id="gpt-sunken-step" />
    <event id="gpt-runeflare-lens" />
    <event id="gpt-bat-swarm-cloud" />
    <event id="gpt-cauldron-spill" />
    <event id="gpt-spiteful-echo" />
    <event id="gpt-bone-shards" />
    <event id="gpt-iron-maiden-door" />
    <event id="gpt-censer-mites" />
    <event id="gpt-furnace-backdraft" />
    <event id="gpt-witch-sigil" />
    <event id="gpt-shallyan-font" />
    <event id="gpt-ranalds-cache" />
    <event id="gpt-ostland-standard" />
    <event id="gpt-kislevite-charm" />
    <event id="gpt-taal-shrine" />
    <event id="gpt-ulrics-embers" />
    <event id="gpt-cartographers-mark" />
    <event id="gpt-middenheim-relief" />
    <event id="gpt-estalian-duelist" />
    <event id="gpt-tilean-contract" />
    <event id="gpt-nehekharan-jar" />
    <event id="gpt-abbot-skeleton" />
    <event id="gpt-amber-wizard-tracks" />
    <event id="gpt-vampires-coffin" />
    <event id="gpt-ironbreakers-oath" />
    <event id="gpt-waywatcher-sign" />
    <event id="gpt-flagellant-graffiti" />
    <event id="gpt-deep-delver-tools" />
    <event id="gpt-river-watch-rune" />
    <event id="gpt-beastmen-totem" />
    <event id="gpt-forgotten-chantry" />
    <event id="gpt-hexensnacht-candles" />
    <event id="gpt-dead-messenger" />
    <event id="gpt-stolen-idol" />
    <event id="gpt-warded-arch" />
    <event id="gpt-mad-prophet" />
    <event id="gpt-buried-powder-horn" />
    <event id="gpt-emerald-moss" />
    <event id="gpt-iron-keyring" />
    <event id="gpt-seer-stone" />
    <event id="gpt-marienburg-lockbox" />
    <event id="gpt-black-ark-trinket" />
    <event id="gpt-sylvan-whisper" />
    <event id="gpt-morrs-lantern" />
    <event id="gpt-wolfshead-helm" />
  </table>
</tables>

=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/rpbook-treasure-tables.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="Roleplay Book - Dungeon Treasure Table" kind="treasure">
    <event id="rpb-treasure-dungeon-heartseeker" />
    <event id="rpb-treasure-dungeon-berserker-sword" />
    <event id="rpb-treasure-dungeon-bronze-sigil-sword" />
    <event id="rpb-treasure-dungeon-boots-of-quargskin" />
    <event id="rpb-treasure-dungeon-sword-of-ensorcelled-iron" />
    <event id="rpb-treasure-dungeon-biting-blade" />
    <event id="rpb-treasure-dungeon-sword-of-stone" />
    <event id="rpb-treasure-dungeon-blade-of-leaping-copper" />
    <event id="rpb-treasure-dungeon-blade-of-couronne" />
    <event id="rpb-treasure-dungeon-magic-sword" />
    <event id="rpb-treasure-dungeon-relic-blade" />
    <event id="rpb-treasure-dungeon-blade-of-slicing" />
    <event id="rpb-treasure-dungeon-darting-steel-blades" />
    <event id="rpb-treasure-dungeon-magical-quiver" />
    <event id="rpb-treasure-dungeon-bone-blade" />
    <event id="rpb-treasure-dungeon-eltharions-bow" />
    <event id="rpb-treasure-dungeon-sword-of-might" />
    <event id="rpb-treasure-dungeon-cloak-of-stealth" />
    <event id="rpb-treasure-dungeon-obsidian-blade" />
    <event id="rpb-treasure-dungeon-giant-slayer" />
    <event id="rpb-treasure-dungeon-sword-of-resilience" />
    <event id="rpb-treasure-dungeon-helmet-of-farseeing" />
    <event id="rpb-treasure-dungeon-parrying-blade" />
    <event id="rpb-treasure-dungeon-deathsword" />
    <event id="rpb-treasure-dungeon-dragonhelm" />
    <event id="rpb-treasure-dungeon-blade-of-sea-gold" />
    <event id="rpb-treasure-dungeon-ogre-slayer" />
    <event id="rpb-treasure-dungeon-blessed-sword" />
    <event id="rpb-treasure-dungeon-grey-armour-of-eshkalon" />
    <event id="rpb-treasure-dungeon-armour-of-fortune" />
    <event id="rpb-treasure-dungeon-undead-bane" />
    <event id="rpb-treasure-dungeon-dispel-magic-scroll" />
    <event id="rpb-treasure-dungeon-energy-jewel" />
    <event id="rpb-treasure-dungeon-amulet-of-fury" />
    <event id="rpb-treasure-dungeon-arrow-of-slaying" />
    <event id="rpb-treasure-dungeon-crown-of-night" />
    <event id="rpb-treasure-dungeon-talisman-of-jet" />
    <event id="rpb-treasure-dungeon-spell-ring" />
    <event id="rpb-treasure-dungeon-destroy-magic-scroll" />
    <event id="rpb-treasure-dungeon-cloak-of-invisibility" />
    <event id="rpb-treasure-dungeon-arrows-of-piercing" />
    <event id="rpb-treasure-dungeon-the-ring-of-dadaan" />
    <event id="rpb-treasure-dungeon-boots-of-leaping" />
    <event id="rpb-treasure-dungeon-boots-of-swiftness" />
    <event id="rpb-treasure-dungeon-boots-of-flight" />
    <event id="rpb-treasure-dungeon-boots-of-battle" />
    <event id="rpb-treasure-dungeon-potion-of-flight" />
    <event id="rpb-treasure-dungeon-potion-of-healing" />
    <event id="rpb-treasure-dungeon-potion-of-invisibility" />
    <event id="rpb-treasure-dungeon-potion-of-strength" />
    <event id="rpb-treasure-dungeon-potion-of-disguise" />
    <event id="rpb-treasure-dungeon-potion-of-water-walking" />
    <event id="rpb-treasure-dungeon-potion-of-toughness" />
    <event id="rpb-treasure-dungeon-protection-ring" />
    <event id="rpb-treasure-dungeon-ring-of-invisibility" />
    <event id="rpb-treasure-dungeon-ring-of-power" />
    <event id="rpb-treasure-dungeon-arkais-powder" />
    <event id="rpb-treasure-dungeon-charm-of-learning" />
    <event id="rpb-treasure-dungeon-ring-of-sure-seeing" />
    <event id="rpb-treasure-dungeon-gems-of-life" />
    <event id="rpb-treasure-dungeon-bracelet-of-transformation" />
    <event id="rpb-treasure-dungeon-lifestone" />
    <event id="rpb-treasure-dungeon-bracelet-of-ashain" />
    <event id="rpb-treasure-dungeon-circlet-of-wrath" />
    <event id="rpb-treasure-dungeon-belt-of-gagron" />
    <event id="rpb-treasure-dungeon-stone-of-transmutation" />
    <event id="rpb-treasure-dungeon-gauntlet-of-damzhar" />
  </table>
  <table name="Roleplay Book - Objective Room Treasure Table" kind="treasure">
    <event id="rpb-treasure-objective-ring-of-seeking" />
    <event id="rpb-treasure-objective-chalice-of-sorcery" />
    <event id="rpb-treasure-objective-enchanted-jade-amulet" />
    <event id="rpb-treasure-objective-book-of-arcane-knowledge" />
    <event id="rpb-treasure-objective-brooch-of-power" />
    <event id="rpb-treasure-objective-wand-of-jade" />
    <event id="rpb-treasure-objective-dawnstone" />
    <event id="rpb-treasure-objective-rune-of-death" />
    <event id="rpb-treasure-objective-crown-of-sorcery" />
    <event id="rpb-treasure-objective-talisman-of-obsidian" />
    <event id="rpb-treasure-objective-tablet-of-adain" />
    <event id="rpb-treasure-objective-armour-of-taakan" />
    <event id="rpb-treasure-objective-wand-of-diabolum" />
    <event id="rpb-treasure-objective-ring-of-cheshnakk" />
    <event id="rpb-treasure-objective-the-hammer-of-sigmar" />
    <event id="rpb-treasure-objective-blade-of-leaping-gold" />
    <event id="rpb-treasure-objective-frostblade" />
    <event id="rpb-treasure-objective-rending-sword" />
    <event id="rpb-treasure-objective-sword-of-destruction" />
    <event id="rpb-treasure-objective-bane-sword" />
    <event id="rpb-treasure-objective-dragon-sword" />
    <event id="rpb-treasure-objective-hellfire-sword" />
    <event id="rpb-treasure-objective-gromril-blade" />
    <event id="rpb-treasure-objective-hydra-sword" />
    <event id="rpb-treasure-objective-sword-of-vengeance" />
    <event id="rpb-treasure-objective-axe-of-slaying" />
    <event id="rpb-treasure-objective-sword-of-heroes" />
    <event id="rpb-treasure-objective-blade-of-leaping-bronze" />
    <event id="rpb-treasure-objective-bow-of-loren" />
    <event id="rpb-treasure-objective-surefire-bow" />
    <event id="rpb-treasure-objective-enchanted-shield" />
    <event id="rpb-treasure-objective-armour-of-meteoric-iron" />
    <event id="rpb-treasure-objective-shield-of-ptolos" />
    <event id="rpb-treasure-objective-armour-of-dargan" />
    <event id="rpb-treasure-objective-spelleater-rune" />
    <event id="rpb-treasure-objective-the-staff-of-command" />
  </table>
</tables>

=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/lm-travel-event-table.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="lm - Travel Hazards Table" kind="travel">
    <event id="lm-travel-imminent-danger-11-12-man-eating-tiger" />
    <event id="lm-travel-imminent-danger-13-14-kidnapped" />
    <event id="lm-travel-imminent-danger-15-16-dragons" />
    <event id="lm-travel-imminent-danger-21-22-harpies" />
    <event id="lm-travel-imminent-danger-23-24-vanished" />
    <event id="lm-travel-imminent-danger-25-26-collapsing-bridge" />
    <event id="lm-travel-imminent-danger-31-32-assassin" />
    <event id="lm-travel-imminent-danger-33-34-hungry-wolves" />
    <event id="lm-travel-imminent-danger-35-36-village-of-the-damned" />
    <event id="lm-travel-imminent-danger-41-42-evil-combatants" />
    <event id="lm-travel-imminent-danger-43-44-river-sprites" />
    <event id="lm-travel-imminent-danger-45-46-ambush" />
    <event id="lm-travel-imminent-danger-51-52-treasure-or-your-life" />
    <event id="lm-travel-imminent-danger-53-54-witch-doctor" />
    <event id="lm-travel-imminent-danger-55-56-food-shortage" />
    <event id="lm-travel-imminent-danger-61-62-brigands" />
    <event id="lm-travel-imminent-danger-63-64-hornets-nest" />
    <event id="lm-travel-imminent-danger-65-66-horsemen" />
    <event id="lm-travel-act-of-nature-11-12-avalanche" />
    <event id="lm-travel-act-of-nature-13-14-quake" />
    <event id="lm-travel-act-of-nature-15-16-heatwave" />
    <event id="lm-travel-act-of-nature-21-22-tornado" />
    <event id="lm-travel-act-of-nature-23-24-plague" />
    <event id="lm-travel-act-of-nature-25-26-volcanic-eruption" />
    <event id="lm-travel-act-of-nature-31-32-famine" />
    <event id="lm-travel-act-of-nature-33-34-forest-fire" />
    <event id="lm-travel-act-of-nature-35-36-lightning" />
    <event id="lm-travel-act-of-nature-41-42-flood" />
    <event id="lm-travel-act-of-nature-43-44-hailstorm" />
    <event id="lm-travel-act-of-nature-45-46-drought" />
    <event id="lm-travel-act-of-nature-51-52-blizzard" />
    <event id="lm-travel-act-of-nature-53-54-rockfall" />
    <event id="lm-travel-act-of-nature-55-56-erosion" />
    <event id="lm-travel-act-of-nature-61-62-dense-fog" />
    <event id="lm-travel-act-of-nature-63-64-glorious-weather" />
    <event id="lm-travel-act-of-nature-65-66-storm" />
    <event id="lm-travel-encounter-11-12-mystic" />
    <event id="lm-travel-encounter-13-14-religious-pilgrims" />
    <event id="lm-travel-encounter-15-16-pedlar" />
    <event id="lm-travel-encounter-21-22-caravan-guards" />
    <event id="lm-travel-encounter-23-24-waylaid" />
    <event id="lm-travel-encounter-25-26-prisoner" />
    <event id="lm-travel-encounter-31-32-merchants" />
    <event id="lm-travel-encounter-33-34-leprechaun" />
    <event id="lm-travel-encounter-35-36-stranger" />
    <event id="lm-travel-encounter-41-42-messenger" />
    <event id="lm-travel-encounter-43-44-dryads" />
    <event id="lm-travel-encounter-45-46-traveller" />
    <event id="lm-travel-encounter-51-52-guide" />
    <event id="lm-travel-encounter-53-54-gypsies" />
    <event id="lm-travel-encounter-55-56-drinks-and-deals" />
    <event id="lm-travel-encounter-61-62-militia" />
    <event id="lm-travel-encounter-63-64-travelling-minstrel" />
    <event id="lm-travel-encounter-65-66-adventuring-party" />
    <event id="lm-travel-structure-or-object-11-12-tower" />
    <event id="lm-travel-structure-or-object-13-14-chapel" />
    <event id="lm-travel-structure-or-object-15-16-strange-brew" />
    <event id="lm-travel-structure-or-object-21-22-dungeon-map" />
    <event id="lm-travel-structure-or-object-23-24-population-marker" />
    <event id="lm-travel-structure-or-object-25-26-wild-mushrooms" />
    <event id="lm-travel-structure-or-object-31-32-giant-nest" />
    <event id="lm-travel-structure-or-object-33-34-bad-map" />
    <event id="lm-travel-structure-or-object-35-36-monolith" />
    <event id="lm-travel-structure-or-object-41-42-damaged-wagon" />
    <event id="lm-travel-structure-or-object-43-44-death-note" />
    <event id="lm-travel-structure-or-object-45-46-hunting-snare" />
    <event id="lm-travel-structure-or-object-51-52-toll-station" />
    <event id="lm-travel-structure-or-object-53-54-tombstone" />
    <event id="lm-travel-structure-or-object-55-56-wagon-train" />
    <event id="lm-travel-structure-or-object-61-62-shrine" />
    <event id="lm-travel-structure-or-object-63-64-cottage" />
    <event id="lm-travel-structure-or-object-65-66-portal" />
    <event id="lm-travel-event-11-12-massacre" />
    <event id="lm-travel-event-13-14-fire" />
    <event id="lm-travel-event-15-16-commotion" />
    <event id="lm-travel-event-21-22-troupe" />
    <event id="lm-travel-event-23-24-unicorn" />
    <event id="lm-travel-event-25-26-guests" />
    <event id="lm-travel-event-31-32-feud" />
    <event id="lm-travel-event-33-34-distressed-villager" />
    <event id="lm-travel-event-35-36-foul-odour" />
    <event id="lm-travel-event-41-42-lost" />
    <event id="lm-travel-event-43-44-warrant" />
    <event id="lm-travel-event-45-46-which-road" />
    <event id="lm-travel-event-51-52-ceremony" />
    <event id="lm-travel-event-53-54-double-back" />
    <event id="lm-travel-event-55-56-mage-battle" />
    <event id="lm-travel-event-61-62-procession" />
    <event id="lm-travel-event-63-64-ransom" />
    <event id="lm-travel-event-65-66-fall" />
    <event id="lm-travel-place-11-12-graveyard" />
    <event id="lm-travel-place-13-14-fire-spring" />
    <event id="lm-travel-place-15-16-bandit-stronghold" />
    <event id="lm-travel-place-21-22-garden" />
    <event id="lm-travel-place-23-24-encampment" />
    <event id="lm-travel-place-25-26-beautiful-grove" />
    <event id="lm-travel-place-31-32-witchs-cave" />
    <event id="lm-travel-place-33-34-chasm" />
    <event id="lm-travel-place-35-36-pool-of-dreams" />
    <event id="lm-travel-place-41-42-checkpoint" />
    <event id="lm-travel-place-43-44-mysterious-hollow" />
    <event id="lm-travel-place-45-46-mausoleum" />
    <event id="lm-travel-place-51-52-magic-glade" />
    <event id="lm-travel-place-53-54-swamp" />
    <event id="lm-travel-place-55-56-den" />
    <event id="lm-travel-place-61-62-waterfall" />
    <event id="lm-travel-place-63-64-abandoned-mine" />
    <event id="lm-travel-place-65-66-battlefield" />
  </table>
</tables>

=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/lm-settlement-event-tables.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="lm - Outside The Gates Events" kind="settlement">
    <event id="lm-outskirts-11-city-watch" />
    <event id="lm-outskirts-12-uneventful-day" />
    <event id="lm-outskirts-13-bandits" />
    <event id="lm-outskirts-14-an-adventure" />
    <event id="lm-outskirts-15-argil-s-magic-emporium" />
    <event id="lm-outskirts-16-beggars" />
    <event id="lm-outskirts-21-bard" />
    <event id="lm-outskirts-22-hay-wagon" />
    <event id="lm-outskirts-23-outbreak" />
    <event id="lm-outskirts-24-horse-thief" />
    <event id="lm-outskirts-25-riot" />
    <event id="lm-outskirts-26-the-black-tiger" />
    <event id="lm-outskirts-31-bad-omen" />
    <event id="lm-outskirts-32-wizard-s-apprentice" />
    <event id="lm-outskirts-33-uneventful-day" />
    <event id="lm-outskirts-34-curse" />
    <event id="lm-outskirts-35-an-adventure" />
    <event id="lm-outskirts-36-animal-rampage" />
    <event id="lm-outskirts-41-stench" />
    <event id="lm-outskirts-42-famished" />
    <event id="lm-outskirts-43-uneventful-day" />
    <event id="lm-outskirts-44-collapse" />
    <event id="lm-outskirts-45-spirit" />
    <event id="lm-outskirts-46-noble" />
    <event id="lm-outskirts-51-pests" />
    <event id="lm-outskirts-52-an-adventure" />
    <event id="lm-outskirts-53-pet-dog" />
    <event id="lm-outskirts-54-lepers" />
    <event id="lm-outskirts-55-madman" />
    <event id="lm-outskirts-56-uneventful-day" />
    <event id="lm-outskirts-61-mysterious-priest" />
    <event id="lm-outskirts-62-healer" />
    <event id="lm-outskirts-63-heavy-rains" />
    <event id="lm-outskirts-64-young-whelp" />
    <event id="lm-outskirts-65-an-adventure" />
    <event id="lm-outskirts-66-admittance" />
  </table>
  <table name="lm - Village Events" kind="settlement">
    <event id="lm-village-11-thrown-out" />
    <event id="lm-village-12-an-adventure" />
    <event id="lm-village-13-hunting" />
    <event id="lm-village-14-uneventful-day" />
    <event id="lm-village-15-witchcraft" />
    <event id="lm-village-16-nightmare" />
    <event id="lm-village-21-well" />
    <event id="lm-village-22-festival" />
    <event id="lm-village-23-family-heirloom" />
    <event id="lm-village-24-runaway" />
    <event id="lm-village-25-illness" />
    <event id="lm-village-26-an-adventure" />
    <event id="lm-village-31-uneventful-day" />
    <event id="lm-village-32-temple-donation" />
    <event id="lm-village-33-river-monster" />
    <event id="lm-village-34-snake" />
    <event id="lm-village-35-accident" />
    <event id="lm-village-36-pacifist" />
    <event id="lm-village-41-pickpocket" />
    <event id="lm-village-42-betrothed" />
    <event id="lm-village-43-friendly-villager" />
    <event id="lm-village-44-an-adventure" />
    <event id="lm-village-45-circus" />
    <event id="lm-village-46-gambling" />
    <event id="lm-village-51-beggars" />
    <event id="lm-village-52-pugilist" />
    <event id="lm-village-53-inheritance" />
    <event id="lm-village-54-fooled" />
    <event id="lm-village-55-riotous-living" />
    <event id="lm-village-56-an-honest-day-s-work" />
    <event id="lm-village-61-fire" />
    <event id="lm-village-62-troubadour" />
    <event id="lm-village-63-pet-dog" />
    <event id="lm-village-64-crime" />
    <event id="lm-village-65-uneventful-day" />
    <event id="lm-village-66-fearful-villagers" />
  </table>
  <table name="lm - Town Events" kind="settlement">
    <event id="lm-town-11-thrown-out" />
    <event id="lm-town-12-well" />
    <event id="lm-town-13-debt" />
    <event id="lm-town-14-investment" />
    <event id="lm-town-15-an-adventure" />
    <event id="lm-town-16-fire" />
    <event id="lm-town-21-fight" />
    <event id="lm-town-22-nightmare" />
    <event id="lm-town-23-drugged" />
    <event id="lm-town-24-family-heirloom" />
    <event id="lm-town-25-accident" />
    <event id="lm-town-26-uneventful-day" />
    <event id="lm-town-31-riotous-living" />
    <event id="lm-town-32-circus" />
    <event id="lm-town-33-crime" />
    <event id="lm-town-34-snake" />
    <event id="lm-town-35-witchcraft" />
    <event id="lm-town-36-pet-dog" />
    <event id="lm-town-41-fooled" />
    <event id="lm-town-42-inheritance" />
    <event id="lm-town-43-an-adventure" />
    <event id="lm-town-44-steam-bath" />
    <event id="lm-town-45-overturned-cart" />
    <event id="lm-town-46-sword-for-sale" />
    <event id="lm-town-51-beggars" />
    <event id="lm-town-52-troubadour" />
    <event id="lm-town-53-an-honest-day-s-work" />
    <event id="lm-town-54-robbery" />
    <event id="lm-town-55-uneventful-day" />
    <event id="lm-town-56-hunting" />
    <event id="lm-town-61-pickpocket" />
    <event id="lm-town-62-runaway" />
    <event id="lm-town-63-jealous-adventurer" />
    <event id="lm-town-64-join-the-watch" />
    <event id="lm-town-65-salesman" />
    <event id="lm-town-66-an-adventure" />
  </table>
  <table name="lm - City Events" kind="settlement">
    <event id="lm-city-11-thrown-out" />
    <event id="lm-city-12-uneventful-day" />
    <event id="lm-city-13-investment" />
    <event id="lm-city-14-pet-dog" />
    <event id="lm-city-15-cutpurse" />
    <event id="lm-city-16-bathhouse" />
    <event id="lm-city-21-an-adventure" />
    <event id="lm-city-22-an-honest-day-s-work" />
    <event id="lm-city-23-riotous-living" />
    <event id="lm-city-24-hunting" />
    <event id="lm-city-25-street-artists" />
    <event id="lm-city-26-counterfeit" />
    <event id="lm-city-31-false-accusation" />
    <event id="lm-city-32-wrestler" />
    <event id="lm-city-33-uneventful-day" />
    <event id="lm-city-34-robbery" />
    <event id="lm-city-35-troubadour" />
    <event id="lm-city-36-tax-collector" />
    <event id="lm-city-41-an-adventure" />
    <event id="lm-city-42-con-artist" />
    <event id="lm-city-43-old-friend" />
    <event id="lm-city-44-good-deed" />
    <event id="lm-city-45-beggars" />
    <event id="lm-city-46-relative" />
    <event id="lm-city-51-criminal" />
    <event id="lm-city-52-parade" />
    <event id="lm-city-53-accident" />
    <event id="lm-city-54-city-watch" />
    <event id="lm-city-55-street-urchin" />
    <event id="lm-city-56-salesman" />
    <event id="lm-city-61-duel" />
    <event id="lm-city-62-an-adventure" />
    <event id="lm-city-63-riot" />
    <event id="lm-city-64-trader" />
    <event id="lm-city-65-reward" />
    <event id="lm-city-66-assassin" />
  </table>
</tables>
