=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/whq-tables-schema.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
     Warhammer Quest Monster and Event table schema.
    </xsd:documentation>
  </xsd:annotation>
  
  <xsd:simpleType name="monsterNumberType">
   <xsd:restriction base="xsd:string">
      <xsd:pattern value="([0-9])*|([0-9]*-[0-9]*)|S|S \(mounts\)"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ambienceValueType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="chaos"/>
      <xsd:enumeration value="undead"/>
      <xsd:enumeration value="skaven"/>
      <xsd:enumeration value="orcs"/>
      <xsd:enumeration value="chaos-dwarves"/>
      <xsd:enumeration value="dark-elves"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ambiencesType">
    <xsd:list itemType="ambienceValueType"/>
  </xsd:simpleType>
  
  <xsd:complexType name="magicType">
    <xsd:attribute name="id"    type="xsd:string"/>
    <xsd:attribute name="level" type="xsd:nonNegativeInteger"/>
  </xsd:complexType>
  
  <xsd:complexType name="ruleType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="param" type="xsd:string"/>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
  
  <xsd:complexType name="specialType">
    <xsd:sequence>
      <xsd:element name="text" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="rule" type="ruleType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="magic" type="magicType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="append" type="xsd:boolean" />
  </xsd:complexType>
  
  <xsd:complexType name="monsterType">
    <xsd:sequence minOccurs="0" maxOccurs="1">
      <xsd:element name="special" type="specialType" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="number" type="monsterNumberType" />
    <xsd:attribute name="level" type="xsd:integer" />
    <xsd:attribute name="ambiences" type="ambiencesType" />
  </xsd:complexType>
  
  <xsd:complexType name="eventType">
    <xsd:attribute name="id" type="xsd:string" />
    <xsd:attribute name="ambiences" type="ambiencesType" />
  </xsd:complexType>
  
  <xsd:complexType name="groupType">
    <xsd:sequence minOccurs="1" maxOccurs="unbounded">
      <xsd:element name="monster" type="monsterType" />
    </xsd:sequence>
    <xsd:attribute name="level" type="xsd:integer" />
  </xsd:complexType>

  <xsd:complexType name="tableRefType">
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="level" type="xsd:integer" />
    <xsd:attribute name="targetLevel" type="xsd:integer" />
    <xsd:attribute name="times" type="xsd:positiveInteger" />
    <xsd:attribute name="ambiences" type="ambiencesType" />
  </xsd:complexType>
  
  <xsd:complexType name="tableType">
    <xsd:sequence maxOccurs="unbounded" minOccurs="1">
      <xsd:choice>
        <xsd:element name="monster" type="monsterType" />
        <xsd:element name="event" type="eventType" />
        <xsd:element name="group" type="groupType" />
        <xsd:element name="tableRef" type="tableRefType" />
      </xsd:choice>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" />
    <xsd:attribute name="kind" type="xsd:string" />
  </xsd:complexType>

  <xsd:element name="tables">
    <xsd:complexType>
      <xsd:sequence maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="table" type="tableType" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
  
</xsd:schema>

=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/originaldeck-table.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="Original Event Deck">
    <monster id="od-giant-bat" number="2-12" ambiences="chaos undead skaven orcs-goblins chaos-dwarves dark-elves" level="1" />
    <monster id="od-giant-rat" number="2-12" ambiences="chaos undead skaven orcs-goblins chaos-dwarves dark-elves" level="1" />
    <monster id="od-giant-spider" number="2-12" ambiences="chaos undead skaven orcs-goblins chaos-dwarves dark-elves" level="1" />
    <monster id="od-snotling" number="2-12" ambiences="orcs-goblins" level="1" />
    <monster id="od-goblin-archer" number="6" ambiences="orcs-goblins" level="1" />
    <monster id="od-goblin-spearman" number="6" ambiences="orcs-goblins" level="1" />
    <group level="1">
      <monster id="od-goblin-archer" number="1-6" ambiences="orcs-goblins" level="1" />
      <monster id="od-goblin-spearman" number="1-6" ambiences="orcs-goblins" level="1" />
    </group>
    <monster id="od-skaven" number="2-12" ambiences="skaven" level="1" />
    <monster id="od-orc" number="6" ambiences="orcs-goblins" level="1" />
    <group level="1">
      <monster id="od-orc" number="1-6" ambiences="orcs-goblins" level="1" />
      <monster id="od-orc-archer" number="1-6" ambiences="orcs-goblins" level="1" />
    </group>
    <monster id="od-minotaur-solo" number="1" ambiences="chaos" level="1" />
    <monster id="od-minotaur" number="1-3" ambiences="chaos" level="1" />
    <event id="od-old-bones" ambiences="undead" />
    <event id="od-scorpions" ambiences="chaos undead skaven orcs-goblins chaos-dwarves dark-elves" />
    <event id="od-encounter" ambiences="chaos undead skaven orcs-goblins chaos-dwarves dark-elves" />
    <event id="od-trap" ambiences="chaos undead skaven orcs-goblins chaos-dwarves dark-elves" />
    <event id="od-dead-body" ambiences="chaos undead skaven orcs-goblins chaos-dwarves dark-elves" />
    <event id="od-portcullis" ambiences="chaos undead skaven orcs-goblins chaos-dwarves dark-elves" />
    <event id="od-cave-in" ambiences="chaos undead skaven orcs-goblins chaos-dwarves dark-elves" />
  </table>
</tables>

=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/cot-dungeon-event-table.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="Catacombs of Terror Dungeon Events">
    <event id="cot-ambush" />
    <event id="cot-ambush" />
    <event id="cot-ambush" />
    <event id="cot-trap-lightning-bolt" />
    <event id="cot-trap-lightning-bolt" />
    <event id="cot-trap-lightning-bolt" />
    <event id="cot-trap-dark-mist-spell" />
    <event id="cot-trap-dark-mist-spell" />
    <event id="cot-trap-dark-mist-spell" />
    <event id="cot-treasury" />
    <event id="cot-treasury" />
    <event id="cot-treasury" />
    <event id="cot-ghost" />
    <event id="cot-ghost" />
    <event id="cot-ghost" />
    <event id="cot-sarcophagus" />
    <event id="cot-sarcophagus" />
    <event id="cot-sarcophagus" />
    <event id="cot-tomb-chamber" />
    <event id="cot-tomb-chamber" />
    <event id="cot-tomb-chamber" />
    <event id="cot-escape-or-die" />
    <event id="cot-escape-or-die" />
    <event id="cot-escape-or-die" />
    <event id="cot-the-pit-of-eternity" />
    <event id="cot-the-pit-of-eternity" />
    <event id="cot-the-pit-of-eternity" />
    <event id="cot-curse-of-years" />
    <event id="cot-curse-of-years" />
    <event id="cot-curse-of-years" />
    <event id="cot-laughter-of-the-damned" />
    <event id="cot-laughter-of-the-damned" />
    <event id="cot-laughter-of-the-damned" />
    <event id="cot-death-rot-fungus" />
    <event id="cot-death-rot-fungus" />
    <event id="cot-death-rot-fungus" />
  </table>
</tables>

=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/lotol-dungeon-event-table.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="Lair of the Orc Lord Dungeon Events">
    <event id="lotol-challenge" />
    <event id="lotol-idol-of-gork" />
    <event id="lotol-idol-of-gork" />
    <event id="lotol-lights-out" />
    <event id="lotol-lights-out" />
    <event id="lotol-lights-out" />
    <event id="lotol-boar-know-wotz" />
    <event id="lotol-boar-know-wotz" />
    <event id="lotol-boar-know-wotz" />
    <event id="lotol-boar-know-wotz" />
    <event id="lotol-orcy-treasure-hoard" />
    <event id="lotol-orcy-treasure-hoard" />
    <event id="lotol-orcy-treasure-hoard" />
    <event id="lotol-orcy-treasure-hoard" />
    <event id="lotol-orcy-treasure-hoard" />
    <event id="lotol-squiglitz" />
    <event id="lotol-squiglitz" />
    <event id="lotol-squiglitz" />
    <event id="lotol-squiglitz" />
    <event id="lotol-squiglitz" />
    <event id="lotol-squiglitz" />
    <event id="lotol-da-evil-eye" />
    <event id="lotol-da-evil-eye" />
    <event id="lotol-da-evil-eye" />
    <event id="lotol-da-evil-eye" />
    <event id="lotol-da-evil-eye" />
    <event id="lotol-spider-bite" />
    <event id="lotol-spider-bite" />
    <event id="lotol-spider-bite" />
    <event id="lotol-spider-bite" />
    <event id="lotol-kruimch" />
    <event id="lotol-kruimch" />
    <event id="lotol-kruimch" />
    <event id="lotol-map" />
    <event id="lotol-map" />
    <event id="lotol-spore-fungus" />
  </table>
</tables>

=== anoguero/whq-helper/WhqHelperApp/data/xml/tables/rpbook-travel-event-table.xml
<?xml version="1.0"?>

<tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation='whq-tables-schema.xsd'>
  <table name="Roleplay Book Travel Hazards Table" kind="travel">
    <event id="rpb-massacre" />
    <event id="rpb-fire" />
    <event id="rpb-chapel" />
    <event id="rpb-quake" />
    <event id="rpb-stranger" />
    <event id="rpb-pedlar" />
    <event id="rpb-tornado" />
    <event id="rpb-travel-22-uneventful-week" />
    <event id="rpb-travel-23-plague" />
    <event id="rpb-travel-24-uneventful-week" />
    <event id="rpb-travel-25-prisoner" />
    <event id="rpb-travel-26-guests" />
    <event id="rpb-travel-31-witchs-cave" />
    <event id="rpb-travel-32-famine" />
    <event id="rpb-travel-33-uneventful-week" />
    <event id="rpb-travel-34-bad-map" />
    <event id="rpb-travel-35-pool-of-dreams" />
    <event id="rpb-travel-36-lightning" />
    <event id="rpb-travel-41-lost" />
    <event id="rpb-travel-42-lightning" />
    <event id="rpb-travel-43-waylaid" />
    <event id="rpb-travel-44-uneventful-week" />
    <event id="rpb-travel-45-which-road" />
    <event id="rpb-travel-46-ambush" />
    <event id="rpb-travel-51-uneventful-week" />
    <event id="rpb-travel-52-blizzard" />
    <event id="rpb-travel-53-double-back" />
    <event id="rpb-travel-54-rockfall" />
    <event id="rpb-travel-55-wagon-train" />
    <event id="rpb-travel-56-uneventful-week" />
    <event id="rpb-travel-61-militia" />
    <event id="rpb-travel-62-brigands" />
    <event id="rpb-travel-63-travelling-minstrel" />
    <event id="rpb-travel-64-fall" />
    <event id="rpb-travel-65-glorious-weather" />
    <event id="rpb-travel-66-storm" />
  </table>
</tables>
