=== anoguero/whq-helper/WhqHelperApp/data/xml/locations/whq-locations-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Warhammer Quest settlement locations schema.
    </xsd:documentation>
  </xsd:annotation>

  <xsd:simpleType name="settlementAvailabilityType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="city"/>
      <xsd:enumeration value="town"/>
      <xsd:enumeration value="village"/>
      <xsd:enumeration value="outskirts"/>
      <xsd:enumeration value="special"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="availableListType">
    <xsd:sequence>
      <xsd:element name="type" type="settlementAvailabilityType" maxOccurs="unbounded" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="visitorListType">
    <xsd:sequence>
      <xsd:element name="visitor" type="xsd:string" maxOccurs="unbounded" minOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="locationType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="available" type="availableListType"/>
      <xsd:element name="description" type="xsd:string"/>
      <xsd:element name="visitors" type="visitorListType"/>
      <xsd:element name="rules" type="xsd:string"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:element name="locations">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="location" type="locationType" maxOccurs="unbounded" minOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== anoguero/whq-helper/WhqHelperApp/data/xml/locations/locations.xml
<?xml version='1.0' encoding='utf-8'?>
<locations xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="whq-locations-schema.xsd">
  <location id="location-enfermeria">
    <name>Enfermería</name>
    <available>
      <type>city</type>
      <type>town</type>
      <type>village</type>
    </available>
    <description>Ya sea un erudito religioso, un curtido médico o un viejo ermitaño, el curandero local ofrece asistencia médica tanto a la gente del pueblo como a los viajeros de paso.</description>
    <visitors>
      <visitor>all</visitor>
    </visitors>
    <rules>Cada vez que un Aventurero se queda a cero Heridas, ya sea por un ataque, hechizo, trampa u otro motivo, y recupera una Herida o más, sufrirá una Lesión o Secuela por esa experiencia cercana a la muerte. Su cuerpo o su mente quedarán marcados con lesiones de mayor gravedad.

El Aventurero deberá robar una carta de Lesión o Secuela al azar, donde se explica la nueva penalización. La acumulación de estas secuelas puede causar la muerte si algún atributo llega a cero.

Una lesión o secuela no puede eliminarse con pociones, vendas o provisiones. En su lugar, debe ser tratada en la Enfermería de un Asentamiento, pagando una cantidad de monedas y permaneciendo aquí el número de días indicado.

La Enfermería también restablece las deducciones permanentes en atributos causadas por Parálisis, Plaga, Petrificar o Veneno a cambio de 50 monedas y 2 días.</rules>
  </location>
  <location id="location-establos">
    <name>Establos</name>
    <available>
      <type>city</type>
      <type>town</type>
      <type>village</type>
    </available>
    <description>Los viajeros pueden dejar a su corcel en los establos. Allí serán alimentados y bien cuidados hasta partir a su próxima aventura.</description>
    <visitors>
      <visitor>all</visitor>
    </visitors>
    <rules>Pago obligatorio por día:
Perro x2
Mula +1
Caballo +2
Caballo de Guerra +3

Si estás utilizando animales de monta procedentes de continentes o países remotos, puedes llevarlos al Viejo Mundo contigo, pero pagando un plus por el transporte del animal. Deberás multiplicar 2D6 por el valor referenciado en cada caso para saber cuánto cuesta llevarlo contigo.

Pago obligatorio por día para monturas exóticas:
Caballo Salvaje de Kislev +2
Gélido de Lustria +2
Camello de Arabia +3
Elefante de Lustria +10</rules>
  </location>
  <location id="location-prision">
    <name>Prisión</name>
    <available>
      <type>city</type>
      <type>town</type>
      <type>village</type>
    </available>
    <description>Te recordamos que cada asentamiento tiene sus propias leyes... ¡Compórtate, viajero, o se hará justicia!</description>
    <visitors>
      <visitor>all</visitor>
    </visitors>
    <rules>Es una localización del asentamiento donde los Aventureros pueden terminar encarcelados durante un número de días determinado como solución a eventos de asentamiento, peleas en tabernas u otras reglas.

Mientras un Aventurero esté en prisión no tiene que pagar gastos diarios en el asentamiento ni debe preocuparse por los eventos del asentamiento o los eventos catastróficos que puedan suceder.</rules>
  </location>
  <location id="location-puertas-de-acceso">
    <name>Puertas de Acceso</name>
    <available>
      <type>city</type>
      <type>town</type>
      <type>village</type>
    </available>
    <description>Cada Aventurero que se quede fuera de los muros del asentamiento está a merced de la tempestad, monstruos o las criaturas más salvajes, entre otros peligros.</description>
    <visitors>
      <visitor>all</visitor>
    </visitors>
    <rules>A veces, los Peligros de Viaje o los Eventos Catastróficos indican a los Aventureros que pasan directamente a la siguiente aventura. También es posible que todos sean “Expulsados” del Asentamiento.

Si tienen ya una aventura predefinida o el Posadero les ha encomendado alguna, parten de inmediato a la misma; pero en caso contrario, si les expulsan, deben tirar D66 en “Aventuras Inmediatas” para saber cuál es la misión a realizar.

Consulta las páginas del Libro de Aventuras Definitivo de Littlemonk para conocer la aventura y sus reglas especiales.

Los Aventureros pueden encontrar estas aventuras las menos gratificantes y/o las más peligrosas, pero no tienen alternativa.</rules>
  </location>
  <location id="location-taberna">
    <name>Taberna</name>
    <available>
      <type>city</type>
      <type>town</type>
      <type>village</type>
    </available>
    <description>Llena de gente extraña e interesantes viajeros, es el lugar perfecto para conocer historias y meterse en líos.</description>
    <visitors>
      <visitor>all</visitor>
    </visitors>
    <rules>La Taberna es la única localización que los Aventureros pueden encontrar automáticamente en cualquier tipo de Asentamiento, incluidas las Aldeas.

Cualquier Aventurero excepto el Bailarín Guerrero puede visitar la Taberna. El Bárbaro, el Enano y otros Aventureros igual de duros no sufren penalizadores en la tabla. Cuando un Aventurero entra en la Taberna debe tirar 2D6 y consultar el resultado. Si es un Elfo, resta 4; si es un Hechicero, resta 3; si es un Sacerdote Guerrero o un Explorador Elfo, resta 2. Cualquier resultado inferior a 2 se considera un 2.

2. Mientras el Aventurero se toma una cerveza, Ragnar el Terrible le vende el supuesto Talismán de Erik por 500 monedas de oro. El talismán es una falsificación. Si el Aventurero no dispone de 500 monedas, entrega todo su oro y además un objeto de tesoro para compensar.

3. El Aventurero acaba muy borracho y pierde 1D6 x 100 monedas de oro.

4. Griswold el Loco apuesta 200 monedas a que el Aventurero no resistirá un combate contra su manada de lobos. Si acepta, 1D3 clientes se unen a la apuesta. Tira 1D6:
1. El Aventurero vence, pero Griswold se queda todas las apuestas para compensar la pérdida de sus animales.
2-3. El Aventurero escapa del pozo de lucha, pero pierde la apuesta.
4-6. El Aventurero hace picadillo a los lobos y cobra todas las apuestas.

5. Rogar el Bizco vende una pócima milagrosa por 100 monedas de oro o un objeto de tesoro, arma o armadura. Cuando el Aventurero la beba tira 1D6:
1-2. No tiene más efecto que provocar náuseas.
3-5. El Aventurero entra en Furia Asesina hasta que todos los monstruos estén muertos.
6. Recupera 1D6 Heridas.

6. Un artista local le hace al Aventurero un tatuaje que representa una cabeza de Orco con sus propios rasgos y la leyenda “Amor de Orco”.

7. El Aventurero vence en un concurso de pulsos. A partir de ahora, cada vez que intente comprar en una tienda de esta Población tira 1D6:
1-2. Le cierran la puerta en las narices.
3-6. Le venden todo a mitad de precio.

8. Un veterano Bárbaro de Norsca enseña al Aventurero a cubrirse con grasa animal para resultar resbaladizo. Una vez por aventura puede utilizar este truco para evitar un golpe que, de otro modo, le habría herido.

9. Los Cantores del Matadero, unos juglares de Erengad, le enseñan al Aventurero una estrofa de “Ella era la única hija del Emperador”. Una vez por aventura puede elegir un monstruo sobre el tablero cuyo valor no supere 300 monedas y tirar 1D6; con 5 o 6 el monstruo muere de un derrame cerebral.

10. El Aventurero termina una noche de bebida siendo el último en pie y aligera los bolsillos del resto de clientes. Consigue (1D6 + 2) x 100 monedas de oro.

11. Un kislevita borracho enseña al Aventurero a hacerse el muerto. Una vez por aventura puede tumbar su miniatura. Mientras finja estar muerto y quede otro Aventurero en pie, ningún monstruo le atacará hasta que se incorpore o no quede ningún otro Aventurero en pie.

12. Un fornido mercenario de Marienburgo enseña al Aventurero a luchar con dos armas a la vez. Una vez por aventura puede efectuar +1 Ataque.

El libro añade además una variante ampliada de Tabernas con refinamiento, peleas de taberna y una tabla extensa de resultados opcionales. Si quieres usar esa versión, se superpone a esta tabla básica.</rules>
  </location>
  <location id="location-alquimista">
    <name>Alquimista</name>
    <available>
      <type>city</type>
      <type>town</type>
      <type>village</type>
    </available>
    <description>¿Necesitas oro de una forma desesperante? El alquimista local puede serte de ayuda con este problema...</description>
    <visitors>
      <visitor>all</visitor>
    </visitors>
    <rules>El laboratorio del Alquimista es un lugar muy curioso, lleno de vapores nocivos y frascos de cristal burbujeantes. Su principal ocupación consiste en convertir metales innobles en oro, y cualquier Aventurero puede recurrir a sus servicios.

El Alquimista toma cualquier artículo sin usar de equipo o una carta de tesoro e intenta transmutarlo. Desecha el objeto o la carta, tira tantos dados como quieras, suma el resultado y multiplica el total por 50. Esa será la cantidad de oro obtenida.

Si en cualquiera de los dados sale un 1, la transmutación fracasa por completo y el objeto se convierte en un charco de lodo.

El Alquimista se queda con la mitad del oro obtenido. Si no consigue nada, no cobra nada.</rules>
  </location>
  <location id="location-fabricante-de-armaduras">
    <name>Fabricante de Armaduras</name>
    <available>
      <type>city</type>
      <type>town</type>
      <type>village</type>
    </available>
    <description>Cuero, cotas de malla, armaduras de placas... Aquí encontrarás toda la protección necesaria para sobrevivir a tu próxima aventura.</description>
    <visitors>
      <visitor>all</visitor>
    </visitors>
    <rules>Cota de Malla. Stock 6+. Compra 500. Venta 150. +2 Resistencia y -1 Movimiento.

Armadura Ligera. Stock 7+. Compra 1000. Venta 350. +2 Resistencia.

Armadura Pesada. Stock 8+. Compra 4000. Venta 1100. +3 Resistencia y -1 Movimiento, excepto para Enanos.

Armadura de Placas. Stock 10+. Compra 8000. Venta 2000. +4 Resistencia. No se puede usar con armas a dos manos.
